<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ========== Категория 1: Смарт-часы ==========
            [
                'name' => 'Apple Watch Series 10',
                'category_id' => 1,
                'price' => 49990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => 'Умные часы с ярким OLED-дисплеем, мониторингом сна, ЭКГ и измерением кислорода в крови. Алюминиевый корпус, защита от воды 50 м.',
            ],
            [
                'name' => 'Apple Watch Ultra 2',
                'category_id' => 1,
                'price' => 74990,
                'discount' => '5%',
                'quantity' => 8,
                'description' => 'Часы для экстремального спорта с титановым корпусом, GPS, барометром и яркостью до 3000 нит.',
            ],
            [
                'name' => 'Samsung Galaxy Watch 7',
                'category_id' => 1,
                'price' => 29990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Смарт-часы с ИИ-анализом сна, ЭКГ и ярким AMOLED-экраном 1.5 дюйма.',
            ],
            [
                'name' => 'Samsung Galaxy Watch Ultra',
                'category_id' => 1,
                'price' => 59990,
                'discount' => '15%',
                'quantity' => 6,
                'description' => 'Прочные титановые часы с GPS, термометром для воды и автономностью до 3 дней.',
            ],
            [
                'name' => 'Garmin Forerunner 265',
                'category_id' => 1,
                'price' => 44990,
                'discount' => '0%',
                'quantity' => 12,
                'description' => 'Спортивные часы для бега с GPS, AMOLED-экраном и продвинутой статистикой тренировок.',
            ],
            [
                'name' => 'Garmin Venu 3',
                'category_id' => 1,
                'price' => 39990,
                'discount' => '10%',
                'quantity' => 10,
                'description' => 'Универсальные часы для фитнеса и здоровья с GPS, мониторингом сна и тренировками йоги.',
            ],
            [
                'name' => 'Huawei Watch GT 5 Pro',
                'category_id' => 1,
                'price' => 32990,
                'discount' => '5%',
                'quantity' => 14,
                'description' => 'Элегантные часы с титановым корпусом, GPS, анализом здоровья по 100+ метрикам.',
            ],
            [
                'name' => 'Xiaomi Watch S3',
                'category_id' => 1,
                'price' => 14990,
                'discount' => '20%',
                'quantity' => 30,
                'description' => 'Доступные часы с AMOLED-экраном, GPS, 150 спортивными режимами и автономностью до 15 дней.',
            ],
            [
                'name' => 'Amazfit GTR 4',
                'category_id' => 1,
                'price' => 12990,
                'discount' => '0%',
                'quantity' => 25,
                'description' => 'Стильные часы с GPS, двухчастотным позиционированием и зарядкой, которой хватает на 14 дней.',
            ],
            [
                'name' => 'Google Pixel Watch 3',
                'category_id' => 1,
                'price' => 24990,
                'discount' => '10%',
                'quantity' => 18,
                'description' => 'Часы с Fitbit-интеграцией, быстрым процессором и ярким дисплеем Always-On.',
            ],

            // ========== Категория 2: Планшеты ==========
            [
                'name' => 'Apple iPad Pro 11 M4',
                'category_id' => 2,
                'price' => 99990,
                'discount' => '5%',
                'quantity' => 10,
                'description' => 'Профессиональный планшет с чипом M4, дисплеем Ultra Retina XDR и поддержкой Apple Pencil Pro.',
            ],
            [
                'name' => 'Apple iPad Air 13 M2',
                'category_id' => 2,
                'price' => 69990,
                'discount' => '5%',
                'quantity' => 12,
                'description' => 'Лёгкий планшет с чипом M2, дисплеем Liquid Retina и поддержкой Apple Pencil Pro.',
            ],
            [
                'name' => 'Samsung Galaxy Tab S10 Ultra',
                'category_id' => 2,
                'price' => 99990,
                'discount' => '10%',
                'quantity' => 8,
                'description' => 'Флагманский планшет 14.6 дюйма с AMOLED-экраном, S Pen и чипом MediaTek Dimensity 9300+.',
            ],
            [
                'name' => 'Samsung Galaxy Tab S10+',
                'category_id' => 2,
                'price' => 79990,
                'discount' => '0%',
                'quantity' => 9,
                'description' => 'Мощный планшет 12.4 дюйма с AMOLED 120 Гц и режимом многозадачности DeX.',
            ],
            [
                'name' => 'Xiaomi Pad 6S Pro',
                'category_id' => 2,
                'price' => 49990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => 'Планшет с 144 Гц 12.4-дюймовым экраном, Snapdragon 8 Gen 2 и быстрой зарядкой 120 Вт.',
            ],
            [
                'name' => 'Huawei MatePad Pro 13.2',
                'category_id' => 2,
                'price' => 54990,
                'discount' => '0%',
                'quantity' => 7,
                'description' => 'Тонкий планшет 13.2 дюйма с OLED-экраном и стилусом M-Pencil.',
            ],
            [
                'name' => 'Lenovo Tab P12',
                'category_id' => 2,
                'price' => 34990,
                'discount' => '15%',
                'quantity' => 20,
                'description' => 'Планшет 12.7 дюйма с 3K-дисплеем, 8 динамиками JBL и поддержкой стилуса.',
            ],
            [
                'name' => 'Microsoft Surface Pro 11',
                'category_id' => 2,
                'price' => 119990,
                'discount' => '5%',
                'quantity' => 5,
                'description' => 'Трансформер 2-в-1 с чипом Snapdragon X Elite, способный заменить ноутбук.',
            ],
            [
                'name' => 'Google Pixel Tablet',
                'category_id' => 2,
                'price' => 39990,
                'discount' => '10%',
                'quantity' => 14,
                'description' => 'Планшет с док-станцией-динамиком, который превращает его в умный дисплей.',
            ],
            [
                'name' => 'Apple iPad 10',
                'category_id' => 2,
                'price' => 32990,
                'discount' => '0%',
                'quantity' => 25,
                'description' => 'Базовый iPad с 10.9-дюймовым дисплеем, чипом A14 и USB-C.',
            ],

            // ========== Категория 3: Телевизоры ==========
            [
                'name' => 'Samsung UE55DU8000 55"',
                'category_id' => 3,
                'price' => 54990,
                'discount' => '0%',
                'quantity' => 8,
                'description' => '4K UHD телевизор 55 дюймов, HDR10+, умная платформа Tizen, тонкий безрамочный дизайн.',
            ],
            [
                'name' => 'LG OLED C4 65"',
                'category_id' => 3,
                'price' => 199990,
                'discount' => '10%',
                'quantity' => 5,
                'description' => 'OLED-телевизор 65 дюймов с безупречным чёрным цветом, 120 Гц и webOS 24.',
            ],
            [
                'name' => 'Sony Bravia XR A80L 55"',
                'category_id' => 3,
                'price' => 169990,
                'discount' => '5%',
                'quantity' => 4,
                'description' => 'OLED с процессором Cognitive Processor XR и звуком Acoustic Surface Audio+.',
            ],
            [
                'name' => 'TCL 55C755 4K QLED',
                'category_id' => 3,
                'price' => 54990,
                'discount' => '20%',
                'quantity' => 12,
                'description' => 'QLED с Mini-LED подсветкой, 144 Гц и игровыми функциями для PS5 и Xbox.',
            ],
            [
                'name' => 'Hisense 65U8KQ 4K',
                'category_id' => 3,
                'price' => 79990,
                'discount' => '15%',
                'quantity' => 9,
                'description' => 'Mini-LED телевизор 65 дюймов с пиковой яркостью 1500 нит и поддержкой Dolby Vision.',
            ],
            [
                'name' => 'Samsung QE65Q80D 4K',
                'category_id' => 3,
                'price' => 129990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'QLED с квантовыми точками, 120 Гц и игровым режимом с переменной частотой обновления.',
            ],
            [
                'name' => 'LG QNED80T 55"',
                'category_id' => 3,
                'price' => 69990,
                'discount' => '10%',
                'quantity' => 10,
                'description' => 'NanoCell-телевизор 55 дюймов с широким углом обзора и тонкими рамками.',
            ],
            [
                'name' => 'Xiaomi TV A2 55"',
                'category_id' => 3,
                'price' => 39990,
                'discount' => '0%',
                'quantity' => 18,
                'description' => 'Бюджетный 4K-телевизор 55 дюймов с Android TV и поддержкой Dolby Vision.',
            ],
            [
                'name' => 'Philips 58PUS8507 4K',
                'category_id' => 3,
                'price' => 54990,
                'discount' => '5%',
                'quantity' => 11,
                'description' => 'Телевизор с фирменной подсветкой Ambilight и платформой Android TV.',
            ],
            [
                'name' => 'Sony Bravia 7 XR55 4K',
                'category_id' => 3,
                'price' => 139990,
                'discount' => '0%',
                'quantity' => 5,
                'description' => 'Mini-LED флагман с процессором XR и яркостью для просмотра в светлых комнатах.',
            ],

            // ========== Категория 4: Аудио ==========
            [
                'name' => 'Sony WH-1000XM5',
                'category_id' => 4,
                'price' => 34990,
                'discount' => '15%',
                'quantity' => 25,
                'description' => 'Беспроводные наушники с шумоподавлением мирового класса и до 30 часов работы.',
            ],
            [
                'name' => 'JBL Charge 5',
                'category_id' => 4,
                'price' => 15990,
                'discount' => '20%',
                'quantity' => 30,
                'description' => 'Портативная Bluetooth-колонка с защитой IP67 и функцией power bank.',
            ],
            [
                'name' => 'Apple AirPods Pro 2',
                'category_id' => 4,
                'price' => 24990,
                'discount' => '5%',
                'quantity' => 40,
                'description' => 'TWS-наушники с адаптивным шумоподавлением, пространственным звуком и USB-C кейсом.',
            ],
            [
                'name' => 'Bose QuietComfort Ultra',
                'category_id' => 4,
                'price' => 42990,
                'discount' => '10%',
                'quantity' => 14,
                'description' => 'Флагманские наушники с иммерсивным звуком Bose и топовым шумоподавлением.',
            ],
            [
                'name' => 'JBL Tune 770NC',
                'category_id' => 4,
                'price' => 9990,
                'discount' => '20%',
                'quantity' => 35,
                'description' => 'Лёгкие беспроводные наушники с активным шумоподавлением и 70 часами работы.',
            ],
            [
                'name' => 'Marshall Stanmore III',
                'category_id' => 4,
                'price' => 44990,
                'discount' => '5%',
                'quantity' => 10,
                'description' => 'Домашняя колонка с винтажным дизайном, мощным звуком и Bluetooth.',
            ],
            [
                'name' => 'Sonos Era 100',
                'category_id' => 4,
                'price' => 29990,
                'discount' => '0%',
                'quantity' => 12,
                'description' => 'Умная колонка с пространственным звуком, AirPlay 2 и управлением голосом.',
            ],
            [
                'name' => 'Sennheiser Momentum 4',
                'category_id' => 4,
                'price' => 29990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => 'Беспроводные наушники премиум-класса с отличным звуком и 60 часами работы.',
            ],
            [
                'name' => 'Xiaomi Redmi Buds 6',
                'category_id' => 4,
                'price' => 3990,
                'discount' => '15%',
                'quantity' => 60,
                'description' => 'Бюджетные TWS-наушники с ANC, пространственным звуком и долгой автономностью.',
            ],
            [
                'name' => 'Yamaha YAS-209',
                'category_id' => 4,
                'price' => 44990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Саундбар с беспроводным сабвуфером, DTS Virtual:X и Alexa.',
            ],

            // ========== Категория 5: Фототехника ==========
            [
                'name' => 'Canon EOS R8',
                'category_id' => 5,
                'price' => 119990,
                'discount' => '0%',
                'quantity' => 5,
                'description' => 'Полнокадровая беззеркальная камера 24.2 Мп, 4K 60p, быстрый автофокус.',
            ],
            [
                'name' => 'Canon EOS R50',
                'category_id' => 5,
                'price' => 74990,
                'discount' => '10%',
                'quantity' => 8,
                'description' => 'Компактная беззеркалка для блогеров с 4K видео и творческим автофокусом.',
            ],
            [
                'name' => 'Sony Alpha A7 IV',
                'category_id' => 5,
                'price' => 239990,
                'discount' => '5%',
                'quantity' => 4,
                'description' => 'Профессиональная полнокадровая камера 33 Мп с 4K 60p и гибридным автофокусом.',
            ],
            [
                'name' => 'Sony ZV-E10 II',
                'category_id' => 5,
                'price' => 99990,
                'discount' => '0%',
                'quantity' => 10,
                'description' => 'Камера для видеоблогов с APS-C сенсором, 4K и встроенным микрофоном.',
            ],
            [
                'name' => 'Nikon Z50 II',
                'category_id' => 5,
                'price' => 89990,
                'discount' => '10%',
                'quantity' => 6,
                'description' => 'Компактная беззеркальная камера с 20.9 Мп, 4K 30p и отличной эргономикой.',
            ],
            [
                'name' => 'Fujifilm X-T50',
                'category_id' => 5,
                'price' => 149990,
                'discount' => '0%',
                'quantity' => 5,
                'description' => 'Беззеркалка с фирменными цветами Fujifilm, 40 Мп и компактным корпусом.',
            ],
            [
                'name' => 'Panasonic Lumix G100',
                'category_id' => 5,
                'price' => 64990,
                'discount' => '15%',
                'quantity' => 9,
                'description' => 'Компактная камера для контент-мейкеров с 4K и системой фокусировки на человека.',
            ],
            [
                'name' => 'GoPro HERO 12',
                'category_id' => 5,
                'price' => 44990,
                'discount' => '20%',
                'quantity' => 15,
                'description' => 'Экшн-камера с 5.3K видео, гиперстабилизацией и водозащитой до 10 м.',
            ],
            [
                'name' => 'DJI Osmo Pocket 3',
                'category_id' => 5,
                'price' => 59990,
                'discount' => '5%',
                'quantity' => 7,
                'description' => 'Карманная камера с 1-дюймовым сенсором и 4K 120 кадров в секунду.',
            ],
            [
                'name' => 'Canon PowerShot G7 X Mark III',
                'category_id' => 5,
                'price' => 79990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Компактная камера с 1-дюймовым сенсором, 4K и поворотным экраном для съёмки себя.',
            ],

            // ========== Категория 6: Умный дом ==========
            [
                'name' => 'Яндекс Станция Мини 2',
                'category_id' => 6,
                'price' => 12990,
                'discount' => '10%',
                'quantity' => 40,
                'description' => 'Умная колонка с Алисой, управлением техникой и сценариями умного дома.',
            ],
            [
                'name' => 'Яндекс Станция Лайт',
                'category_id' => 6,
                'price' => 6990,
                'discount' => '10%',
                'quantity' => 50,
                'description' => 'Компактная колонка с Алисой, 8 световых зон и хорошим звуком для своей цены.',
            ],
            [
                'name' => 'Яндекс Станция Макс 2',
                'category_id' => 6,
                'price' => 24990,
                'discount' => '5%',
                'quantity' => 15,
                'description' => 'Мощная колонка с объёмным звуком, Zigbee-хабом и дисплеем.',
            ],
            [
                'name' => 'Google Nest Hub 2nd Gen',
                'category_id' => 6,
                'price' => 14990,
                'discount' => '0%',
                'quantity' => 12,
                'description' => 'Умный дисплей с Google Assistant, функцией сна и управлением домом.',
            ],
            [
                'name' => 'Amazon Echo Dot 5',
                'category_id' => 6,
                'price' => 9990,
                'discount' => '15%',
                'quantity' => 20,
                'description' => 'Компактная колонка с Alexa, встроенным датчиком температуры.',
            ],
            [
                'name' => 'Apple HomePod mini',
                'category_id' => 6,
                'price' => 11990,
                'discount' => '0%',
                'quantity' => 18,
                'description' => 'Умная колонка с Siri, потрясающим звуком и работой в связке с HomeKit.',
            ],
            [
                'name' => 'Xiaomi Smart Home Hub',
                'category_id' => 6,
                'price' => 5990,
                'discount' => '10%',
                'quantity' => 25,
                'description' => 'Центр умного дома Xiaomi с Zigbee и поддержкой 100+ устройств.',
            ],
            [
                'name' => 'Roborock S8 MaxV Ultra',
                'category_id' => 6,
                'price' => 89990,
                'discount' => '5%',
                'quantity' => 8,
                'description' => 'Робот-пылесос с самоочисткой, шваброй с возвратно-поступательным движением.',
            ],
            [
                'name' => 'Aqara Camera Hub G3',
                'category_id' => 6,
                'price' => 9990,
                'discount' => '0%',
                'quantity' => 14,
                'description' => 'Умная камера с Zigbee-хабом, распознаванием лиц и поворотом на 360°.',
            ],
            [
                'name' => 'Philips Hue Bridge',
                'category_id' => 6,
                'price' => 8990,
                'discount' => '10%',
                'quantity' => 22,
                'description' => 'Хаб для управления лампами Philips Hue и сценариями освещения.',
            ],

            // ========== Категория 7: Мониторы ==========
            [
                'name' => 'LG UltraGear 27GS95QE 27"',
                'category_id' => 7,
                'price' => 89990,
                'discount' => '0%',
                'quantity' => 12,
                'description' => 'Игровой OLED-монитор 27 дюймов, 2K 240 Гц, отклик 0.03 мс.',
            ],
            [
                'name' => 'Dell UltraSharp U2723QE 27"',
                'category_id' => 7,
                'price' => 57990,
                'discount' => '5%',
                'quantity' => 14,
                'description' => '4K IPS монитор с USB-C хабом 90 Вт для дизайнеров и офиса.',
            ],
            [
                'name' => 'Samsung Odyssey OLED G8 34"',
                'category_id' => 7,
                'price' => 139990,
                'discount' => '10%',
                'quantity' => 6,
                'description' => 'Изогнутый OLED 34 дюйма, 3440x1440, 175 Гц и насыщенные цвета.',
            ],
            [
                'name' => 'ASUS ROG Swift PG27AQDM 27"',
                'category_id' => 7,
                'price' => 119990,
                'discount' => '5%',
                'quantity' => 7,
                'description' => 'Игровой OLED 27 дюймов, 2K 240 Гц, отклик 0.03 мс и G-Sync.',
            ],
            [
                'name' => 'Gigabyte M28U 28"',
                'category_id' => 7,
                'price' => 45990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => '4K IPS монитор 144 Гц с HDMI 2.1 для консолей и ПК.',
            ],
            [
                'name' => 'LG UltraGear 27GP850 27"',
                'category_id' => 7,
                'price' => 34990,
                'discount' => '15%',
                'quantity' => 20,
                'description' => 'Nano IPS 2K 165 Гц (разгон до 180 Гц) с отличной цветопередачей.',
            ],
            [
                'name' => 'BenQ PD3225U 32"',
                'category_id' => 7,
                'price' => 99990,
                'discount' => '0%',
                'quantity' => 5,
                'description' => '4K UHD монитор для дизайнеров с покрытием 98% DCI-P3 и Thunderbolt 3.',
            ],
            [
                'name' => 'Samsung ViewFinity S9 27"',
                'category_id' => 7,
                'price' => 89990,
                'discount' => '5%',
                'quantity' => 8,
                'description' => '5K монитор с Tizen и встроенной веб-камерой 4K для конференций.',
            ],
            [
                'name' => 'MSI MAG 271QPX 27"',
                'category_id' => 7,
                'price' => 69990,
                'discount' => '0%',
                'quantity' => 9,
                'description' => 'OLED 2K 360 Гц с минимальным откликом для киберспорта.',
            ],
            [
                'name' => 'Philips 279P1 27"',
                'category_id' => 7,
                'price' => 42990,
                'discount' => '10%',
                'quantity' => 13,
                'description' => '4K IPS монитор с USB-C 65 Вт, подходящий для работы и дома.',
            ],

            // ========== Категория 8: Телефоны ==========
            [
                'name' => 'Apple iPhone 15 Pro 256GB',
                'category_id' => 8,
                'price' => 119990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Флагман с титановым корпусом, чипом A17 Pro и камерой 48 Мп.',
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'category_id' => 8,
                'price' => 109990,
                'discount' => '15%',
                'quantity' => 18,
                'description' => 'Смартфон с S Pen, Galaxy AI, камерой 200 Мп и титановой рамкой.',
            ],
            [
                'name' => 'Google Pixel 9 Pro',
                'category_id' => 8,
                'price' => 99990,
                'discount' => '0%',
                'quantity' => 16,
                'description' => 'Смартфон с профессиональной камерой, чипом Tensor G4 и ИИ-функциями.',
            ],
            [
                'name' => 'Apple iPhone 16 128GB',
                'category_id' => 8,
                'price' => 89990,
                'discount' => '5%',
                'quantity' => 30,
                'description' => 'Актуальный iPhone с чипом A18, кнопкой управления камерой и Apple Intelligence.',
            ],
            [
                'name' => 'Samsung Galaxy S24 128GB',
                'category_id' => 8,
                'price' => 69990,
                'discount' => '10%',
                'quantity' => 22,
                'description' => 'Компактный флагман с Galaxy AI, отличным экраном и камерой 50 Мп.',
            ],
            [
                'name' => 'OnePlus 12 16/512GB',
                'category_id' => 8,
                'price' => 74990,
                'discount' => '5%',
                'quantity' => 15,
                'description' => 'Смартфон с камерой Hasselblad, Snapdragon 8 Gen 3 и зарядкой 100 Вт.',
            ],
            [
                'name' => 'Xiaomi 14 Ultra 512GB',
                'category_id' => 8,
                'price' => 89990,
                'discount' => '10%',
                'quantity' => 12,
                'description' => 'Фотомонстр с камерой Leica 1-дюйм и четверной оптикой.',
            ],
            [
                'name' => 'Huawei Pura 70 Ultra',
                'category_id' => 8,
                'price' => 109990,
                'discount' => '0%',
                'quantity' => 8,
                'description' => 'Смартфон с выдвижной камерой 50 Мп с механическим изменением диафрагмы.',
            ],
            [
                'name' => 'Nothing Phone (2a) 12/256GB',
                'category_id' => 8,
                'price' => 34990,
                'discount' => '15%',
                'quantity' => 28,
                'description' => 'Стильный смартфон с подсветкой Glyph, чистым Android и отличным ценником.',
            ],
            [
                'name' => 'Realme GT 6 12/256GB',
                'category_id' => 8,
                'price' => 54990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Игровой смартфон с Snapdragon 8s Gen 3 и зарядкой 120 Вт.',
            ],

            // ========== Категория 9: Ноутбуки ==========
            [
                'name' => 'Apple MacBook Pro 14 M4',
                'category_id' => 9,
                'price' => 199990,
                'discount' => '5%',
                'quantity' => 9,
                'description' => 'Профессиональный ноутбук с чипом M4 Pro и автономностью до 22 часов.',
            ],
            [
                'name' => 'ASUS ROG Zephyrus G16',
                'category_id' => 9,
                'price' => 189990,
                'discount' => '0%',
                'quantity' => 7,
                'description' => 'Игровой ноутбук с RTX 4070, Ryzen 9 и OLED 240 Гц.',
            ],
            [
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'category_id' => 9,
                'price' => 159990,
                'discount' => '10%',
                'quantity' => 11,
                'description' => 'Бизнес-ультрабук весом 1.08 кг с автономностью до 18 часов.',
            ],
            [
                'name' => 'Apple MacBook Air 13 M3',
                'category_id' => 9,
                'price' => 119990,
                'discount' => '5%',
                'quantity' => 20,
                'description' => 'Тонкий и лёгкий ноутбук с чипом M3, безвентиляторной системой и дисплеем Liquid Retina.',
            ],
            [
                'name' => 'ASUS Zenbook 14 OLED',
                'category_id' => 9,
                'price' => 89990,
                'discount' => '10%',
                'quantity' => 16,
                'description' => 'Лёгкий ультрабук с OLED 2.8K, Ryzen 7 и металлическим корпусом.',
            ],
            [
                'name' => 'HP Spectre x360 16',
                'category_id' => 9,
                'price' => 149990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Трансформер с OLED-экраном, процессором Core Ultra 7 и стилусом.',
            ],
            [
                'name' => 'Dell XPS 13',
                'category_id' => 9,
                'price' => 99990,
                'discount' => '10%',
                'quantity' => 14,
                'description' => 'Минималистичный ультрабук с InfinityEdge-экраном и Core Ultra.',
            ],
            [
                'name' => 'Acer Swift Go 14',
                'category_id' => 9,
                'price' => 69990,
                'discount' => '15%',
                'quantity' => 18,
                'description' => 'Доступный ноутбук с OLED 2.8K и процессором Intel Core Ultra 5.',
            ],
            [
                'name' => 'Xiaomi Book Pro 16',
                'category_id' => 9,
                'price' => 99990,
                'discount' => '5%',
                'quantity' => 8,
                'description' => 'Ноутбук с 16-дюймовым 3.1K OLED-экраном и Core Ultra 7.',
            ],
            [
                'name' => 'Huawei MateBook X Pro',
                'category_id' => 9,
                'price' => 129990,
                'discount' => '0%',
                'quantity' => 7,
                'description' => 'Ультратонкий ноутбук весом 980 г с сенсорным OLED-дисплеем.',
            ],

            // ========== Категория 10: Консоли ==========
            [
                'name' => 'Sony PlayStation 5 Pro',
                'category_id' => 10,
                'price' => 74990,
                'discount' => '0%',
                'quantity' => 13,
                'description' => 'Консоль нового поколения с 4K 60 FPS, трассировкой лучей и SSD 2 ТБ.',
            ],
            [
                'name' => 'Xbox Series X',
                'category_id' => 10,
                'price' => 49990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => 'Мощная консоль Microsoft с 12 TFLOPS графики и 4K 120 Гц.',
            ],
            [
                'name' => 'Nintendo Switch 2',
                'category_id' => 10,
                'price' => 45990,
                'discount' => '0%',
                'quantity' => 20,
                'description' => 'Гибридная консоль с большим экраном и контроллерами Joy-Con 2.',
            ],
            [
                'name' => 'Sony PlayStation 5 Slim',
                'category_id' => 10,
                'price' => 54990,
                'discount' => '10%',
                'quantity' => 25,
                'description' => 'Компактная версия PS5 с SSD 1 ТБ и съёмным дисководом.',
            ],
            [
                'name' => 'Xbox Series S',
                'category_id' => 10,
                'price' => 29990,
                'discount' => '5%',
                'quantity' => 22,
                'description' => 'Доступная цифровая консоль с 1440p и Game Pass.',
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'category_id' => 10,
                'price' => 29990,
                'discount' => '0%',
                'quantity' => 18,
                'description' => 'Гибридная консоль с ярким OLED-экраном 7 дюймов.',
            ],
            [
                'name' => 'Steam Deck OLED',
                'category_id' => 10,
                'price' => 64990,
                'discount' => '10%',
                'quantity' => 10,
                'description' => 'Портативная консоль от Valve с OLED-экраном и доступом к Steam.',
            ],
            [
                'name' => 'ASUS ROG Ally X',
                'category_id' => 10,
                'price' => 64990,
                'discount' => '5%',
                'quantity' => 8,
                'description' => 'Портативный игровой ПК с Ryzen Z1 Extreme и Windows 11.',
            ],
            [
                'name' => 'Lenovo Legion Go',
                'category_id' => 10,
                'price' => 64990,
                'discount' => '0%',
                'quantity' => 7,
                'description' => 'Портативная консоль с 8.8-дюймовым QHD-экраном и съёмными контроллерами.',
            ],
            [
                'name' => 'Analogue Pocket',
                'category_id' => 10,
                'price' => 34990,
                'discount' => '10%',
                'quantity' => 5,
                'description' => 'Карманная ретро-консоль с FPGA и поддержкой картриджей Game Boy.',
            ],

            // ========== Категория 11: Клавиатуры ==========
            [
                'name' => 'Keychron Q3 Pro',
                'category_id' => 11,
                'price' => 18990,
                'discount' => '5%',
                'quantity' => 22,
                'description' => 'Механическая клавиатура 75% с алюминиевым корпусом и hot-swap свитчами.',
            ],
            [
                'name' => 'Logitech MX Keys S',
                'category_id' => 11,
                'price' => 12990,
                'discount' => '10%',
                'quantity' => 30,
                'description' => 'Беспроводная клавиатура с подсветкой и интеллектуальными клавишами.',
            ],
            [
                'name' => 'Keychron V6',
                'category_id' => 11,
                'price' => 8990,
                'discount' => '5%',
                'quantity' => 25,
                'description' => 'Механическая клавиатура 100% с QMK/VIA и hot-swap.',
            ],
            [
                'name' => 'Logitech G915 X LIGHTSPEED',
                'category_id' => 11,
                'price' => 24990,
                'discount' => '15%',
                'quantity' => 12,
                'description' => 'Беспроводная игровая клавиатура с механическими свитчами GL.',
            ],
            [
                'name' => 'Razer BlackWidow V4 75%',
                'category_id' => 11,
                'price' => 19990,
                'discount' => '0%',
                'quantity' => 15,
                'description' => 'Горячая замена свитчей Razer Orange, звукоизоляция и RGB.',
            ],
            [
                'name' => 'Corsair K70 RGB PRO',
                'category_id' => 11,
                'price' => 15990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Механическая клавиатура с быстрыми свитчами OPX и алюминиевой рамой.',
            ],
            [
                'name' => 'SteelSeries Apex Pro TKL',
                'category_id' => 11,
                'price' => 24990,
                'discount' => '5%',
                'quantity' => 10,
                'description' => 'Клавиатура с магнитными свитчами OmniPoint и настраиваемым ходом клавиш.',
            ],
            [
                'name' => 'Duck One 3 Mini',
                'category_id' => 11,
                'price' => 12990,
                'discount' => '0%',
                'quantity' => 18,
                'description' => 'Компактная 60% клавиатура с Cherry MX и двухцветными кейкапами.',
            ],
            [
                'name' => 'Epomaker TH80 Pro',
                'category_id' => 11,
                'price' => 9990,
                'discount' => '20%',
                'quantity' => 28,
                'description' => 'Бюджетная механическая 75% с гасчётными свитчами и тримодальным подключением.',
            ],
            [
                'name' => 'Das Keyboard 6 Pro',
                'category_id' => 11,
                'price' => 18990,
                'discount' => '0%',
                'quantity' => 8,
                'description' => 'Профессиональная механическая клавиатура с Cherry MX Brown.',
            ],

            // ========== Категория 12: Мыши ==========
            [
                'name' => 'Logitech MX Master 3S',
                'category_id' => 12,
                'price' => 9990,
                'discount' => '10%',
                'quantity' => 35,
                'description' => 'Эргономичная мышь с бесшумными кликами и бесконечным колесом.',
            ],
            [
                'name' => 'Logitech G Pro X Superlight 2',
                'category_id' => 12,
                'price' => 16990,
                'discount' => '5%',
                'quantity' => 20,
                'description' => 'Ультралёгкая игровая мышь 60 г с сенсором HERO 2 и 32K DPI.',
            ],
            [
                'name' => 'Razer DeathAdder V3 Pro',
                'category_id' => 12,
                'price' => 14990,
                'discount' => '10%',
                'quantity' => 18,
                'description' => 'Лёгкая беспроводная мышь с сенсором Focus Pro 30K.',
            ],
            [
                'name' => 'Razer Viper V2 Pro',
                'category_id' => 12,
                'price' => 14990,
                'discount' => '15%',
                'quantity' => 16,
                'description' => 'Симметричная игровая мышь 58 г с оптическим сенсором Razer 30K.',
            ],
            [
                'name' => 'Logitech G502 X',
                'category_id' => 12,
                'price' => 9990,
                'discount' => '0%',
                'quantity' => 25,
                'description' => 'Игровая мышь с настраиваемым весом и переключателями LIGHTFORCE.',
            ],
            [
                'name' => 'Logitech MX Anywhere 3S',
                'category_id' => 12,
                'price' => 9990,
                'discount' => '10%',
                'quantity' => 28,
                'description' => 'Компактная мышь для путешествий с бесшумными кликами и 8K DPI.',
            ],
            [
                'name' => 'SteelSeries Rival 3',
                'category_id' => 12,
                'price' => 2990,
                'discount' => '20%',
                'quantity' => 40,
                'description' => 'Бюджетная игровая мышь с сенсором TrueMove Core и RGB.',
            ],
            [
                'name' => 'ASUS ROG Harpe Ace',
                'category_id' => 12,
                'price' => 12990,
                'discount' => '0%',
                'quantity' => 14,
                'description' => 'Лёгкая беспроводная мышь 54 г, разработанная с pro-геймерами.',
            ],
            [
                'name' => 'Zowie EC2-CW',
                'category_id' => 12,
                'price' => 14990,
                'discount' => '5%',
                'quantity' => 12,
                'description' => 'Беспроводная эргономичная мышь с проверенной формой EC.',
            ],
            [
                'name' => 'Apple Magic Mouse',
                'category_id' => 12,
                'price' => 8990,
                'discount' => '0%',
                'quantity' => 22,
                'description' => 'Беспроводная мышь с Multi-Touch поверхностью и зарядкой через USB-C.',
            ],

            // ========== Категория 13: Накопители ==========
            [
                'name' => 'Samsung T9 2TB',
                'category_id' => 13,
                'price' => 25990,
                'discount' => '0%',
                'quantity' => 17,
                'description' => 'Портативный SSD 2 ТБ со скоростью до 2000 МБ/с.',
            ],
            [
                'name' => 'Samsung 990 PRO 1TB NVMe',
                'category_id' => 13,
                'price' => 14990,
                'discount' => '10%',
                'quantity' => 30,
                'description' => 'NVMe SSD 1 ТБ с чтением до 7450 МБ/с для ПК и PS5.',
            ],
            [
                'name' => 'WD Black SN850X 2TB',
                'category_id' => 13,
                'price' => 19990,
                'discount' => '5%',
                'quantity' => 18,
                'description' => 'Игровой NVMe SSD 2 ТБ с чтением до 7300 МБ/с.',
            ],
            [
                'name' => 'Kingston Fury Renegade 2TB',
                'category_id' => 13,
                'price' => 16990,
                'discount' => '0%',
                'quantity' => 20,
                'description' => 'NVMe SSD с агрессивным охлаждением и скоростью до 7300 МБ/с.',
            ],
            [
                'name' => 'SanDisk Extreme 1TB',
                'category_id' => 13,
                'price' => 9990,
                'discount' => '15%',
                'quantity' => 25,
                'description' => 'Надёжный портативный SSD с защитой IP65 и скоростью 1050 МБ/с.',
            ],
            [
                'name' => 'Seagate FireCuda 2TB',
                'category_id' => 13,
                'price' => 15990,
                'discount' => '10%',
                'quantity' => 15,
                'description' => 'Портативный игровой SSD 2 ТБ со скоростью 2000 МБ/с.',
            ],
            [
                'name' => 'Lexar Professional 2TB',
                'category_id' => 13,
                'price' => 14990,
                'discount' => '0%',
                'quantity' => 14,
                'description' => 'NVMe SSD для создателей контента со скоростью 7000 МБ/с.',
            ],
            [
                'name' => 'Crucial X10 Pro 1TB',
                'category_id' => 13,
                'price' => 11990,
                'discount' => '5%',
                'quantity' => 16,
                'description' => 'Портативный SSD с USB 3.2 и скоростью 2100 МБ/с.',
            ],
            [
                'name' => 'WD My Passport 4TB',
                'category_id' => 13,
                'price' => 12990,
                'discount' => '10%',
                'quantity' => 22,
                'description' => 'Классический внешний HDD 4 ТБ с аппаратным шифрованием.',
            ],
            [
                'name' => 'Samsung Bar Plus 256GB',
                'category_id' => 13,
                'price' => 2990,
                'discount' => '0%',
                'quantity' => 50,
                'description' => 'Прочная флешка в металлическом корпусе со скоростью 400 МБ/с.',
            ],

            // ========== Категория 14: Роутеры ==========
            [
                'name' => 'TP-Link Archer AX55',
                'category_id' => 14,
                'price' => 9990,
                'discount' => '20%',
                'quantity' => 28,
                'description' => 'Wi-Fi 6 роутер до 3000 Мбит/с с гигабитными портами.',
            ],
            [
                'name' => 'ASUS ROG Rapture GT-AX11000',
                'category_id' => 14,
                'price' => 34990,
                'discount' => '10%',
                'quantity' => 8,
                'description' => 'Трибандовый игровой роутер с Wi-Fi 6 и суммарной скоростью 11 Гбит/с.',
            ],
            [
                'name' => 'ASUS RT-AX86U Pro',
                'category_id' => 14,
                'price' => 24990,
                'discount' => '5%',
                'quantity' => 12,
                'description' => 'Мощный Wi-Fi 6 роутер с оптимизацией для игр и мультиплеера.',
            ],
            [
                'name' => 'TP-Link Archer AX3000',
                'category_id' => 14,
                'price' => 6990,
                'discount' => '15%',
                'quantity' => 35,
                'description' => 'Доступный Wi-Fi 6 роутер со скоростью до 3 Гбит/с.',
            ],
            [
                'name' => 'MikroTik hAP ax3',
                'category_id' => 14,
                'price' => 12990,
                'discount' => '0%',
                'quantity' => 14,
                'description' => 'Роутер для продвинутых пользователей с RouterOS и Wi-Fi 6.',
            ],
            [
                'name' => 'Keenetic Giant KN-2311',
                'category_id' => 14,
                'price' => 11990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Совместимый с российскими провайдерами роутер с Wi-Fi 6.',
            ],
            [
                'name' => 'Xiaomi Router AX3000T',
                'category_id' => 14,
                'price' => 4990,
                'discount' => '0%',
                'quantity' => 40,
                'description' => 'Бюджетный Wi-Fi 6 роутер с простой настройкой через приложение.',
            ],
            [
                'name' => 'Netgear Nighthawk AX5400',
                'category_id' => 14,
                'price' => 19990,
                'discount' => '20%',
                'quantity' => 10,
                'description' => 'Wi-Fi 6 роутер с 4 антеннами и мощным усилителем сигнала.',
            ],
            [
                'name' => 'TP-Link Deco X50 Mesh',
                'category_id' => 14,
                'price' => 15990,
                'discount' => '5%',
                'quantity' => 16,
                'description' => 'Mesh-система из двух модулей для бесшовного Wi-Fi по всему дому.',
            ],
            [
                'name' => 'Ubiquiti UniFi Dream Router',
                'category_id' => 14,
                'price' => 29990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Профессиональный роутер с UniFi Network и Firewall.',
            ],

            // ========== Категория 15: Принтеры ==========
            [
                'name' => 'HP LaserJet M111w',
                'category_id' => 15,
                'price' => 14990,
                'discount' => '0%',
                'quantity' => 19,
                'description' => 'Компактный лазерный принтер с Wi-Fi и мобильной печатью.',
            ],
            [
                'name' => 'Canon PIXMA G1420',
                'category_id' => 15,
                'price' => 19990,
                'discount' => '10%',
                'quantity' => 14,
                'description' => 'Струйный принтер с СНПЧ и ресурсом до 9000 страниц.',
            ],
            [
                'name' => 'Epson L3250',
                'category_id' => 15,
                'price' => 24990,
                'discount' => '5%',
                'quantity' => 16,
                'description' => 'Принтер с системой непрерывной подачи чернил и печатью 4500 стр/мес.',
            ],
            [
                'name' => 'Brother HL-L3210CW',
                'category_id' => 15,
                'price' => 24990,
                'discount' => '15%',
                'quantity' => 12,
                'description' => 'Цветной лазерный принтер с Wi-Fi и двусторонней печатью.',
            ],
            [
                'name' => 'HP LaserJet Pro M404dn',
                'category_id' => 15,
                'price' => 34990,
                'discount' => '0%',
                'quantity' => 8,
                'description' => 'Офисный лазерный принтер со скоростью 38 страниц в минуту.',
            ],
            [
                'name' => 'Canon imageCLASS MF3010',
                'category_id' => 15,
                'price' => 19990,
                'discount' => '10%',
                'quantity' => 13,
                'description' => 'МФУ с печатью, сканированием и копированием, монохромный лазер.',
            ],
            [
                'name' => 'Epson EcoTank L8050',
                'category_id' => 15,
                'price' => 42990,
                'discount' => '5%',
                'quantity' => 6,
                'description' => 'Фотопринтер с СНПЧ и высоким качеством печати A4.',
            ],
            [
                'name' => 'Brother DCP-L2550DW',
                'category_id' => 15,
                'price' => 29990,
                'discount' => '0%',
                'quantity' => 10,
                'description' => 'МФУ с печатью, сканером, копиром и Wi-Fi.',
            ],
            [
                'name' => 'Samsung M2020W',
                'category_id' => 15,
                'price' => 14990,
                'discount' => '20%',
                'quantity' => 18,
                'description' => 'Компактный монохромный принтер с Wi-Fi и мобильной печатью.',
            ],
            [
                'name' => 'Xerox Phaser 3020BI',
                'category_id' => 15,
                'price' => 15990,
                'discount' => '0%',
                'quantity' => 11,
                'description' => 'Лазерный принтер для дома с Wi-Fi и скоростью 20 стр/мин.',
            ],

            // ========== Категория 16: Игровые аксессуары ==========
            [
                'name' => 'Sony DualSense Edge',
                'category_id' => 16,
                'price' => 22990,
                'discount' => '5%',
                'quantity' => 21,
                'description' => 'Профессиональный геймпад для PS5 со сменными стиками.',
            ],
            [
                'name' => 'Sony DualSense',
                'category_id' => 16,
                'price' => 14990,
                'discount' => '10%',
                'quantity' => 35,
                'description' => 'Беспроводной геймпад с адаптивными триггерами и тактильной отдачей.',
            ],
            [
                'name' => 'Xbox Wireless Controller',
                'category_id' => 16,
                'price' => 9990,
                'discount' => '15%',
                'quantity' => 40,
                'description' => 'Стандартный геймпад для Xbox Series и Windows.',
            ],
            [
                'name' => 'Logitech G29 Racing Wheel',
                'category_id' => 16,
                'price' => 39990,
                'discount' => '10%',
                'quantity' => 8,
                'description' => 'Гоночный руль с обратной связью и педалями для симуляторов.',
            ],
            [
                'name' => 'Thrustmaster T248',
                'category_id' => 16,
                'price' => 39990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Гибридный руль с тремя режимами силы обратной связи.',
            ],
            [
                'name' => 'Razer Wolverine V3 Pro',
                'category_id' => 16,
                'price' => 17990,
                'discount' => '5%',
                'quantity' => 12,
                'description' => 'Профессиональный беспроводной геймпад с быстрыми триггерами.',
            ],
            [
                'name' => '8BitDo Ultimate 2.4G',
                'category_id' => 16,
                'price' => 5990,
                'discount' => '0%',
                'quantity' => 30,
                'description' => 'Стильный геймпад с док-станцией и обратной совместимостью.',
            ],
            [
                'name' => 'Nintendo Switch Pro Controller',
                'category_id' => 16,
                'price' => 8990,
                'discount' => '10%',
                'quantity' => 25,
                'description' => 'Полноразмерный геймпад для Nintendo Switch с HD-вибрацией.',
            ],
            [
                'name' => 'Turtle Beach Recon 70',
                'category_id' => 16,
                'price' => 3990,
                'discount' => '20%',
                'quantity' => 28,
                'description' => 'Игровая гарнитура с мощными 40-мм динамиками.',
            ],
            [
                'name' => 'HyperX Cloud III',
                'category_id' => 16,
                'price' => 12990,
                'discount' => '0%',
                'quantity' => 20,
                'description' => 'Игровая гарнитура с объёмным звуком DTS и алюминиевым каркасом.',
            ],

            // ========== Категория 17: Дроны ==========
            [
                'name' => 'DJI Mini 4 Pro',
                'category_id' => 17,
                'price' => 84990,
                'discount' => '0%',
                'quantity' => 6,
                'description' => 'Компактный дрон 249 г с 4K HDR и обходом препятствий.',
            ],
            [
                'name' => 'DJI Air 3',
                'category_id' => 17,
                'price' => 139990,
                'discount' => '10%',
                'quantity' => 5,
                'description' => 'Дрон с двумя камерами 48 Мп и временем полёта до 46 минут.',
            ],
            [
                'name' => 'DJI Mini 3',
                'category_id' => 17,
                'price' => 54990,
                'discount' => '15%',
                'quantity' => 9,
                'description' => 'Лёгкий дрон с камерой 4K и режимом вертикальной съёмки.',
            ],
            [
                'name' => 'DJI Avata 2',
                'category_id' => 17,
                'price' => 119990,
                'discount' => '0%',
                'quantity' => 4,
                'description' => 'FPV-дрон с очками, стабилизацией и записью 4K 60fps.',
            ],
            [
                'name' => 'DJI Phantom 4 Pro V2.0',
                'category_id' => 17,
                'price' => 199990,
                'discount' => '5%',
                'quantity' => 3,
                'description' => 'Профессиональный дрон с камерой 1 дюйм и 5 направлениями обхода.',
            ],
            [
                'name' => 'Autel EVO Nano',
                'category_id' => 17,
                'price' => 79990,
                'discount' => '0%',
                'quantity' => 5,
                'description' => 'Компактный дрон 249 г с камерой 48 Мп и 4K видео.',
            ],
            [
                'name' => 'Autel EVO Lite+',
                'category_id' => 17,
                'price' => 109990,
                'discount' => '10%',
                'quantity' => 4,
                'description' => 'Дрон с 1-дюймовой камерой и 6 направлениями обхода препятствий.',
            ],
            [
                'name' => 'Hubsan Zino Mini Pro',
                'category_id' => 17,
                'price' => 54990,
                'discount' => '0%',
                'quantity' => 7,
                'description' => 'Складной дрон 249 г с 8K-камерой и обходом препятствий.',
            ],
            [
                'name' => 'Potensic Atom',
                'category_id' => 17,
                'price' => 39990,
                'discount' => '15%',
                'quantity' => 8,
                'description' => 'Доступный дрон с 4K 30fps камерой и GPS.',
            ],
            [
                'name' => 'Ryze Tello',
                'category_id' => 17,
                'price' => 9990,
                'discount' => '0%',
                'quantity' => 25,
                'description' => 'Учебный мини-дрон с программированием и камерой 720p.',
            ],

            // ========== Категория 18: Электронные книги ==========
            [
                'name' => 'PocketBook InkPad 4',
                'category_id' => 18,
                'price' => 29990,
                'discount' => '10%',
                'quantity' => 24,
                'description' => 'Ридер 7.8" с E-Ink Carta, влагозащитой IPX8 и подсветкой.',
            ],
            [
                'name' => 'Amazon Kindle Paperwhite',
                'category_id' => 18,
                'price' => 24990,
                'discount' => '10%',
                'quantity' => 30,
                'description' => 'Популярный ридер 7" с тёплой подсветкой и защитой IPX8.',
            ],
            [
                'name' => 'Amazon Kindle',
                'category_id' => 18,
                'price' => 14990,
                'discount' => '5%',
                'quantity' => 35,
                'description' => 'Компактный ридер с E-Ink-дисплеем и автономностью до 6 недель.',
            ],
            [
                'name' => 'Amazon Kindle Scribe',
                'category_id' => 18,
                'price' => 44990,
                'discount' => '0%',
                'quantity' => 10,
                'description' => 'Ридер 10.2" с пером для заметок и чтения документов.',
            ],
            [
                'name' => 'PocketBook Verse Pro',
                'category_id' => 18,
                'price' => 14990,
                'discount' => '10%',
                'quantity' => 28,
                'description' => 'Компактный ридер 6" с E-Ink Carta 1200 и подсветкой ComfortLight.',
            ],
            [
                'name' => 'PocketBook Touch Lux 5',
                'category_id' => 18,
                'price' => 11990,
                'discount' => '0%',
                'quantity' => 26,
                'description' => 'Бюджетный ридер 6" с подсветкой и поддержкой всех форматов.',
            ],
            [
                'name' => 'Kobo Clara 2E',
                'category_id' => 18,
                'price' => 14990,
                'discount' => '15%',
                'quantity' => 18,
                'description' => 'Ридер 6" из переработанного пластика с тёплой подсветкой.',
            ],
            [
                'name' => 'Kobo Libra 2',
                'category_id' => 18,
                'price' => 22990,
                'discount' => '5%',
                'quantity' => 14,
                'description' => 'Ридер 7" с перелистывающими кнопками и защитой от воды.',
            ],
            [
                'name' => 'Boox Page',
                'category_id' => 18,
                'price' => 24990,
                'discount' => '0%',
                'quantity' => 12,
                'description' => 'Ридер на Android с 7" E-Ink Carta и приложениями для чтения.',
            ],
            [
                'name' => 'Boox Tab Mini C',
                'category_id' => 18,
                'price' => 34990,
                'discount' => '10%',
                'quantity' => 8,
                'description' => 'Цветной ридер 7.8" с E-Ink Kaleido 3 и Android.',
            ],

            // ========== Категория 19: Веб-камеры ==========
            [
                'name' => 'Logitech Brio 4K',
                'category_id' => 19,
                'price' => 21990,
                'discount' => '0%',
                'quantity' => 26,
                'description' => 'Веб-камера 4K Ultra HD с HDR и полем зрения до 90°.',
            ],
            [
                'name' => 'Logitech StreamCam',
                'category_id' => 19,
                'price' => 15990,
                'discount' => '10%',
                'quantity' => 18,
                'description' => 'Веб-камера для стримов с 1080p 60fps и вертикальной съёмкой.',
            ],
            [
                'name' => 'Logitech C920 Pro',
                'category_id' => 19,
                'price' => 8990,
                'discount' => '15%',
                'quantity' => 40,
                'description' => 'Классическая веб-камера Full HD 1080p с автофокусом.',
            ],
            [
                'name' => 'Logitech C922 Pro',
                'category_id' => 19,
                'price' => 11990,
                'discount' => '5%',
                'quantity' => 22,
                'description' => 'Веб-камера 1080p 60fps с фоновым размытием для стримов.',
            ],
            [
                'name' => 'Razer Kiyo Pro Ultra',
                'category_id' => 19,
                'price' => 29990,
                'discount' => '0%',
                'quantity' => 8,
                'description' => 'Веб-камера 4K с крупным сенсором и отличной цветопередачей.',
            ],
            [
                'name' => 'Elgato Facecam',
                'category_id' => 19,
                'price' => 19990,
                'discount' => '10%',
                'quantity' => 12,
                'description' => 'Веб-камера для стримеров с сенсором Sony и без сжатия видео.',
            ],
            [
                'name' => 'Insta360 Link',
                'category_id' => 19,
                'price' => 34990,
                'discount' => '5%',
                'quantity' => 6,
                'description' => 'Умная веб-камера с трекингом человека и жестовым управлением.',
            ],
            [
                'name' => 'AVerMedia PW315',
                'category_id' => 19,
                'price' => 9990,
                'discount' => '0%',
                'quantity' => 15,
                'description' => 'Веб-камера Full HD 1080p 60fps с широким углом обзора.',
            ],
            [
                'name' => 'Microsoft LifeCam HD-3000',
                'category_id' => 19,
                'price' => 2990,
                'discount' => '20%',
                'quantity' => 35,
                'description' => 'Бюджетная веб-камера 720p для конференций.',
            ],
            [
                'name' => 'Anker PowerConf C200',
                'category_id' => 19,
                'price' => 14990,
                'discount' => '0%',
                'quantity' => 14,
                'description' => 'Веб-камера 2K с ИИ-кадрированием и двойным микрофоном.',
            ],

            // ========== Категория 20: Зарядные устройства ==========
            [
                'name' => 'Anker GaN 65W',
                'category_id' => 20,
                'price' => 3990,
                'discount' => '15%',
                'quantity' => 50,
                'description' => 'GaN-зарядка 65 Вт с двумя USB-C и одним USB-A.',
            ],
            [
                'name' => 'Anker 735 GaNPrime 65W',
                'category_id' => 20,
                'price' => 5990,
                'discount' => '10%',
                'quantity' => 40,
                'description' => 'Компактная GaN-зарядка 65 Вт для ноутбука и телефона.',
            ],
            [
                'name' => 'Anker PowerPort III 65W',
                'category_id' => 20,
                'price' => 4990,
                'discount' => '5%',
                'quantity' => 35,
                'description' => 'Однопортовая зарядка 65 Вт с протоколом Power Delivery.',
            ],
            [
                'name' => 'Baseus GaN5 100W',
                'category_id' => 20,
                'price' => 6990,
                'discount' => '15%',
                'quantity' => 30,
                'description' => 'GaN-зарядка 100 Вт с 3 портами для нескольких устройств.',
            ],
            [
                'name' => 'Xiaomi 120W Turbo',
                'category_id' => 20,
                'price' => 3990,
                'discount' => '0%',
                'quantity' => 45,
                'description' => 'Сверхбыстрая зарядка 120 Вт с поддержкой HyperCharge.',
            ],
            [
                'name' => 'Ugreen Nexode 140W',
                'category_id' => 20,
                'price' => 8990,
                'discount' => '10%',
                'quantity' => 20,
                'description' => 'Мощная GaN-зарядка 140 Вт с USB-C PD 3.1.',
            ],
            [
                'name' => 'Belkin BoostCharge 65W',
                'category_id' => 20,
                'price' => 5990,
                'discount' => '0%',
                'quantity' => 25,
                'description' => 'GaN-зарядка 65 Вт с двумя USB-C и сертификацией USB-IF.',
            ],
            [
                'name' => 'Samsung 45W Super Fast',
                'category_id' => 20,
                'price' => 3990,
                'discount' => '10%',
                'quantity' => 40,
                'description' => 'Зарядка 45 Вт для технологии Super Fast Charging 2.0.',
            ],
            [
                'name' => 'Apple 35W Dual USB-C',
                'category_id' => 20,
                'price' => 4990,
                'discount' => '5%',
                'quantity' => 30,
                'description' => 'Компактная зарядка Apple на 35 Вт с двумя портами USB-C.',
            ],
            [
                'name' => 'RAVPower 61W GaN',
                'category_id' => 20,
                'price' => 3990,
                'discount' => '20%',
                'quantity' => 28,
                'description' => 'GaN-зарядка 61 Вт для MacBook и других ноутбуков.',
            ],
        ];

        foreach ($products as $product) {
            $seed = Str::slug($product['name']);

            Product::updateOrCreate(
                ['name' => $product['name']],
                array_merge($product, [
                    'imageUrl' => "/images/products/{$seed}.jpg",
                ])
            );
        }
    }
}
